import { escapeHtml } from '../../core/escape-html.js';
import '../../anatomy/chest.js';
import '../../anatomy/biceps.js';
import '../../anatomy/triceps.js';
import '../../anatomy/shoulders.js';
import '../../anatomy/back.js';
import '../../anatomy/abs.js';
import '../../anatomy/quads.js';
import '../../anatomy/hamstrings.js';
import '../../anatomy/calves.js';

const schedule = [
  { day: 1, short: 'PUSH A', title: 'Chest + Biceps', exercises: 7, sets: 24, minutes: 72, asset: '/anatomy/push-a.webp', fallback: 'biceps' },
  { day: 2, short: 'LEGS A', title: 'Legs Heavy + Abs', exercises: 8, sets: 29, minutes: 88, anatomy: ['quads', 'hamstrings', 'abs'] },
  { day: 3, short: 'PULL A', title: 'Back + Triceps', exercises: 8, sets: 27, minutes: 82, anatomy: ['back', 'triceps'] },
  { day: 4, short: 'PUSH B', title: 'Shoulders + Chest', exercises: 5, sets: 20, minutes: 64, anatomy: ['shoulders', 'chest'] },
  { day: 5, short: 'LEGS B', title: 'Legs Hypertrophy + Abs', exercises: 8, sets: 30, minutes: 86, anatomy: ['quads', 'hamstrings', 'calves'] },
  { day: 6, short: 'ARMS', title: 'Arms + Shoulders', exercises: 8, sets: 27, minutes: 76, anatomy: ['biceps', 'triceps', 'shoulders'] },
];
const weekLabels = ['M','T','W','T','F','S','S'];
const blobUrls = new Map();
function greeting(){const h=new Date().getHours();return h<12?'בוקר טוב':h<18?'צהריים טובים':'ערב טוב'}
function nearestWorkout(){const d=new Date().getDay();const t=schedule.find(x=>x.day===d);if(t)return{...t,timing:'היום'};const n=schedule.find(x=>x.day>d)||schedule[0];return{...n,timing:d===0?'מחר':'האימון הבא'}}
function dataUrlToBlobUrl(dataUrl,key){if(blobUrls.has(key))return blobUrls.get(key);if(typeof dataUrl!=='string'||!dataUrl.startsWith('data:image/'))return null;try{const c=dataUrl.indexOf(','),h=dataUrl.slice(0,c),p=dataUrl.slice(c+1),m=h.match(/^data:([^;]+)/)?.[1]||'image/webp',b=atob(p),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);const u=URL.createObjectURL(new Blob([a],{type:m}));blobUrls.set(key,u);return u}catch{return null}}
export function hydrateHomeArt(root=document){const assets=window.IRONLOG_ANATOMY_ASSETS||{};root.querySelectorAll('img[data-home-art]').forEach(image=>{const figure=image.closest('.home-body');const visual=image.closest('.home-anatomy');const fallbackName=image.dataset.fallback;const fallback=fallbackName?dataUrlToBlobUrl(assets[fallbackName],`fallback-${fallbackName}`):null;const reveal=()=>{figure?.classList.add('is-loaded');visual?.classList.add('is-loaded')};const fail=()=>{if(fallback&&image.src!==fallback){image.src=fallback;return}figure?.classList.add('is-unavailable');if(!visual?.querySelector('.home-body:not(.is-unavailable)'))visual?.classList.add('is-unavailable')};image.addEventListener('load',reveal);image.addEventListener('error',fail);if(image.complete){if(image.naturalWidth>0)reveal();else fail()}})}
function anatomyVisual(workout){const assets=window.IRONLOG_ANATOMY_ASSETS||{};const items=workout.asset?[{src:workout.asset,fallback:workout.fallback}]:(workout.anatomy||[]).map(name=>({src:dataUrlToBlobUrl(assets[name],name),fallback:name})).filter(x=>x.src);if(!items.length)return'';return `<div class="home-anatomy" aria-label="שרירי המטרה של ${escapeHtml(workout.title)}"><div class="home-anatomy__glow" aria-hidden="true"></div><div class="home-anatomy__bodies">${items.map(item=>`<div class="home-body"><img data-home-art src="${escapeHtml(item.src)}" ${item.fallback?`data-fallback="${escapeHtml(item.fallback)}"`:''} alt=""></div>`).join('')}</div></div>`}
function weekActivity(currentDay){const activity=[72,44,83,58,76,51,12];return weekLabels.map((label,index)=>{const jsDay=index<6?index+1:0,planned=schedule.some(x=>x.day===jsDay),current=jsDay===currentDay;return `<div class="home-day ${current?'is-today':''} ${planned?'is-planned':''}"><div class="home-day__line"><i style="--activity:${planned?activity[index]:8}%"></i><b></b></div><span>${label}</span></div>`}).join('')}
export function HomeScreen({userName='מתאמן'}={}){const safeName=escapeHtml(userName),workout=nearestWorkout(),currentDay=new Date().getDay(),weeklySets=schedule.reduce((t,x)=>t+x.sets,0),weeklyMinutes=schedule.reduce((t,x)=>t+x.minutes,0);return `<div class="home-art animate-enter" dir="rtl"><header class="home-art__header"><div><span>${greeting()},</span><h1>${safeName}<b>.</b></h1></div><span class="home-pulse" aria-hidden="true">⌁</span></header><section class="home-workout" aria-label="האימון הקרוב"><div class="home-workout__copy"><span class="home-kicker">${workout.timing} · NEXT WORKOUT</span><h2>${workout.short}</h2><h3>${workout.title}</h3><div class="home-workout-meta"><span><strong>${workout.exercises}</strong><small>תרגילים</small></span><span><strong>${workout.sets}</strong><small>סטים</small></span><span><strong>~${workout.minutes}</strong><small>דק׳</small></span></div><button class="home-start" type="button" data-route="workouts"><span>פתח אימון</span><i>↗</i></button></div>${anatomyVisual(workout)}</section><section class="home-metrics" aria-label="סיכום תוכנית שבועי"><div><strong>6</strong><small>ימי אימון</small></div><div><strong>${weeklySets}</strong><small>סטים השבוע</small></div><div><strong>${Math.round(weeklyMinutes/60)}h</strong><small>זמן מתוכנן</small></div></section><section class="home-activity" aria-label="פעילות שבועית"><div class="home-activity__heading"><div><span class="home-kicker">CALENDAR ACTIVITY</span><h3>השבוע שלך</h3></div><span>${currentDay===0?'REST DAY':'ACTIVE WEEK'}</span></div><div class="home-week">${weekActivity(currentDay)}</div></section></div>`}
