(() => {
  'use strict';

  if (window.__IRONLOG_BIGSCREEN_V6__) return;
  window.__IRONLOG_BIGSCREEN_V6__ = true;

  const FRONT_IMG = 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Muscular_system.svg/960px-Muscular_system.svg.png';
  const BACK_IMG = 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Muscular_system-back.svg/960px-Muscular_system-back.svg.png';
  const FALLBACK_PHOTO = 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Young%20man%20lifting%20dumbbell%20weight%20for%20exercise%20in%20fitness%20gym.jpg?width=360';

  const backZones = new Set(['back', 'triceps', 'hamstrings', 'glutes', 'calves']);
  const crops = {
    shoulders: '80 105 840 500', chest: '150 150 700 540', back: '120 90 760 700', biceps: '35 205 930 610', triceps: '35 205 930 610', abs: '220 290 560 650', glutes: '180 545 640 470', quads: '150 590 700 610', hamstrings: '150 590 700 620', calves: '180 850 640 520', generic: '0 0 1000 1400'
  };

  const exactThumbs = {
    'incline-smith':'_ZrCd4IDNSU','chest-press-machine':'pLofEAcfsO8','barbell-curl':'dDI8ClxRS04','preacher-curl':'Zbs3ko8ycyg','cable-curl':'dDI8ClxRS04','lat-pulldown':'GL3h256d6JM','seated-cable-row':'lJoozxC0Rns','cable-crunch':'36HK6uPM_PQ','leg-press-heavy':'hiI-JdtEGIs','leg-press-volume':'hiI-JdtEGIs','rear-delt-machine':'vJYkqD7a0gM','rear-delt-fly':'vJYkqD7a0gM','overhead-cable-ext':'GzmlxvSFE7A','overhead-cable-ext-b':'GzmlxvSFE7A'
  };
  const fallbackThumbs = {chest:'pLofEAcfsO8',biceps:'dDI8ClxRS04',triceps:'GzmlxvSFE7A',back:'GL3h256d6JM',shoulders:'vJYkqD7a0gM',legs:'hiI-JdtEGIs',abs:'36HK6uPM_PQ',generic:'pLofEAcfsO8'};

  const style = document.createElement('style');
  style.id = 'ironlog-bigscreen-v7-polish';
  style.textContent = String.raw`
.workout-view{background:radial-gradient(ellipse 48% 41% at 50% 42%,rgba(145,160,170,.075),transparent 69%),radial-gradient(ellipse 72% 56% at 50% 75%,rgba(31,40,45,.075),transparent 74%),linear-gradient(180deg,#020608 0%,#04080b 53%,#020608 100%)!important}
.big-header{border-bottom-color:rgba(31,41,47,.025)!important;background:transparent!important}
.big-workout-content{grid-template-rows:70px minmax(0,1fr) 120px 59px 72px!important;gap:7px!important;padding-top:3px!important}
.big-title-block{align-content:start!important;padding-top:0!important}.big-title-block h1{font-size:clamp(33px,8.8vw,46px)!important;line-height:.95!important;margin-bottom:7px!important}.big-title-block h1.title-long{font-size:clamp(26px,6.9vw,36px)!important}.big-title-block h1.title-very-long{font-size:clamp(22px,5.9vw,30px)!important}
.big-hero-layout{grid-template-columns:minmax(118px,1.03fr) minmax(160px,1.36fr) minmax(118px,.99fr)!important;gap:0!important;align-items:center!important}.set-progress-panel{transform:translateY(1.5%)!important}
.big-ring{width:clamp(140px,36.5vw,160px)!important;height:clamp(140px,36.5vw,160px)!important}.big-ring:after{inset:9px!important}.big-ring strong{font-size:clamp(42px,10.8vw,52px)!important}.big-ring .ring-label{font-size:10px!important}.big-ring .ring-caption{font-size:9px!important}
.anatomy-stage{transform:translateY(-2.5%)!important;overflow:visible!important;isolation:isolate!important}.anatomy-glow{width:220px!important;height:350px!important;background:radial-gradient(circle,rgba(176,191,201,.085),rgba(207,255,0,.01) 49%,transparent 75%)!important;filter:blur(16px)!important}
.v6-body-photo{position:absolute;z-index:1;left:50%;top:50%;height:min(112%,460px);width:auto;max-width:225px;transform:translate(-50%,-50%) scale(1.03);object-fit:contain;filter:grayscale(1) brightness(.34) contrast(1.62) saturate(0) drop-shadow(0 25px 34px rgba(0,0,0,.66));opacity:.99;pointer-events:none;user-select:none;-webkit-user-drag:none}
.anatomy-stage>.anatomy-figure{z-index:2!important;height:min(112%,460px)!important;width:min(112%,330px)!important;max-width:none!important;filter:drop-shadow(0 0 8px rgba(207,255,0,.07))!important;overflow:visible!important}.anatomy-stage>.anatomy-figure image{display:none!important}.v6-highlight{fill:#cfff00;stroke:#e7ff65;stroke-width:5.5;opacity:.72;mix-blend-mode:screen;filter:drop-shadow(0 0 7px rgba(207,255,0,.56)) drop-shadow(0 0 13px rgba(207,255,0,.22))}
.muscle-target-card{height:180px!important;transform:translateY(1.5%)!important;padding:14px 8px 9px!important;border-color:rgba(56,68,75,.29)!important;background:linear-gradient(150deg,rgba(14,20,24,.74),rgba(5,10,13,.91))!important;box-shadow:inset 0 1px 0 rgba(255,255,255,.01),0 15px 38px rgba(0,0,0,.1)!important}.muscle-target-card strong{font-size:14.5px!important;line-height:1.08!important;margin:8px 0 3px!important}.muscle-target-card small{font-size:8.5px!important}
.mini-anatomy-wrap{position:relative!important;width:92px!important;height:89px!important;margin-top:auto!important;overflow:hidden!important;border-radius:13px!important;background:radial-gradient(circle,rgba(124,139,148,.068),transparent 71%)!important}.v6-mini-photo{position:absolute;z-index:1;left:50%;top:50%;height:176px;width:auto;max-width:none;object-fit:contain;filter:grayscale(1) brightness(.38) contrast(1.56) saturate(0);transform:translate(-50%,-50%);opacity:.99;pointer-events:none}.mini-anatomy-wrap svg{position:relative!important;z-index:2!important;width:100%!important;height:100%!important;max-width:none!important;transform:none!important;filter:none!important}.mini-anatomy-wrap svg image{display:none!important}.mini-anatomy-wrap .v6-highlight{stroke-width:7;opacity:.78;filter:drop-shadow(0 0 7px rgba(207,255,0,.48))}
.big-metrics,.big-metric{height:120px!important;min-height:120px!important}.big-metric{border-color:rgba(49,60,67,.29)!important;background:linear-gradient(150deg,rgba(13,19,23,.75),rgba(5,10,13,.92))!important}.big-metric strong{font-size:clamp(27px,7.3vw,34px)!important;font-weight:800!important}.big-metric.active{border-color:rgba(117,139,43,.42)!important;background:linear-gradient(150deg,rgba(18,26,13,.78),rgba(7,13,9,.93))!important}
.big-actions{height:59px!important}.dark-action,.lime-action{height:59px!important}.lime-action{background:linear-gradient(135deg,#cef100,#b6dc00)!important;border-color:#c8e817!important;box-shadow:0 7px 21px rgba(191,229,0,.065)!important}.dark-action{border-color:rgba(50,61,68,.31)!important}
.next-exercise-strip{height:72px!important;min-height:72px!important;border-color:rgba(48,59,66,.29)!important;background:linear-gradient(150deg,rgba(12,18,22,.78),rgba(5,10,13,.92))!important;grid-template-columns:34px minmax(0,1fr) 56px 26px!important}.next-thumb{width:53px!important;height:53px!important;border-color:rgba(74,85,92,.32)!important;background:#0b1013!important}.next-thumb img{width:100%!important;height:100%!important;object-fit:cover!important;transform:none!important;filter:saturate(.76) contrast(1.08) brightness(.76)!important}.next-exercise-strip strong{font-size:15.5px!important}.next-exercise-strip small{font-size:9px!important}
.rest-controls:not([hidden]){display:none!important}.workout-view.rest-tools-open .rest-controls:not([hidden]){display:grid!important;position:fixed!important;z-index:150!important;left:50%!important;bottom:calc(var(--safe-bottom) + 132px)!important;width:min(calc(100vw - 38px),390px)!important;transform:translateX(-50%)!important;padding:7px!important;border:1px solid rgba(82,98,45,.58)!important;border-radius:17px!important;background:rgba(8,13,11,.98)!important;box-shadow:0 22px 62px rgba(0,0,0,.64)!important}.rest-controls{pointer-events:auto!important}.rest-controls .mini-btn{min-height:43px!important}
@media(max-width:390px){.big-workout-content{grid-template-rows:68px minmax(0,1fr) 116px 57px 68px!important;gap:6px!important;padding-left:7px!important;padding-right:7px!important}.big-hero-layout{grid-template-columns:minmax(111px,1fr) minmax(148px,1.32fr) minmax(111px,.98fr)!important}.big-ring{width:136px!important;height:136px!important}.v6-body-photo{height:min(110%,435px);max-width:210px;transform:translate(-50%,-50%) scale(1.02)}.anatomy-stage>.anatomy-figure{height:min(110%,435px)!important;width:min(110%,310px)!important}.muscle-target-card{height:170px!important}.mini-anatomy-wrap{width:84px!important;height:82px!important}.v6-mini-photo{height:164px}.big-metrics,.big-metric{height:116px!important;min-height:116px!important}.next-exercise-strip{height:68px!important;min-height:68px!important}.next-thumb{width:50px!important;height:50px!important}}
@media(max-height:760px){.big-workout-content{grid-template-rows:64px minmax(0,1fr) 98px 51px 57px!important;gap:5px!important}.big-title-block h1{font-size:clamp(26px,7vw,35px)!important}.big-ring{width:114px!important;height:114px!important}.v6-body-photo{height:min(108%,342px);max-width:168px}.anatomy-stage>.anatomy-figure{height:min(108%,342px)!important;width:min(108%,244px)!important}.muscle-target-card{height:138px!important}.mini-anatomy-wrap{width:68px!important;height:66px!important}.v6-mini-photo{height:124px}.big-metrics,.big-metric{height:98px!important;min-height:98px!important}.big-actions,.dark-action,.lime-action{height:51px!important}.next-exercise-strip{height:57px!important;min-height:57px!important}.next-thumb{width:42px!important;height:42px!important}}
`;
  document.head.appendChild(style);

  function zoneFromClass(node){if(!node)return'generic';const cls=Array.from(node.classList).find(c=>c.startsWith('zone-')&&c!=='zone-generic');return cls?cls.slice(5):'generic'}
  function imageForZone(zone){return backZones.has(zone)?BACK_IMG:FRONT_IMG}
  function highlightMarkup(zone){const shapes={shoulders:'<ellipse class="v6-highlight" cx="215" cy="285" rx="135" ry="105"/><ellipse class="v6-highlight" cx="785" cy="285" rx="135" ry="105"/>',chest:'<path class="v6-highlight" d="M265 260 Q500 180 735 260 L700 510 Q500 580 300 510Z"/>',back:'<path class="v6-highlight" d="M245 235 Q500 130 755 235 L705 650 Q500 760 295 650Z"/>',biceps:'<ellipse class="v6-highlight" cx="190" cy="485" rx="92" ry="175"/><ellipse class="v6-highlight" cx="810" cy="485" rx="92" ry="175"/>',triceps:'<ellipse class="v6-highlight" cx="185" cy="495" rx="88" ry="185"/><ellipse class="v6-highlight" cx="815" cy="495" rx="88" ry="185"/>',abs:'<path class="v6-highlight" d="M370 430 Q500 385 630 430 L610 795 Q500 850 390 795Z"/>',glutes:'<ellipse class="v6-highlight" cx="405" cy="785" rx="135" ry="105"/><ellipse class="v6-highlight" cx="595" cy="785" rx="135" ry="105"/>',quads:'<ellipse class="v6-highlight" cx="385" cy="900" rx="105" ry="245"/><ellipse class="v6-highlight" cx="615" cy="900" rx="105" ry="245"/>',hamstrings:'<ellipse class="v6-highlight" cx="385" cy="925" rx="100" ry="240"/><ellipse class="v6-highlight" cx="615" cy="925" rx="100" ry="240"/>',calves:'<ellipse class="v6-highlight" cx="390" cy="1180" rx="82" ry="205"/><ellipse class="v6-highlight" cx="610" cy="1180" rx="82" ry="205"/>'};return shapes[zone]||''}

  function ensureMainPhoto(){const stage=document.querySelector('.anatomy-stage');if(!stage)return null;let img=stage.querySelector('.v6-body-photo');if(!img){img=document.createElement('img');img.className='v6-body-photo';img.alt='';img.decoding='async';img.referrerPolicy='no-referrer';stage.prepend(img)}return img}
  function renderMainAnatomy(){const svg=document.getElementById('anatomyFigure');if(!svg)return;const zone=zoneFromClass(svg);const img=ensureMainPhoto();const src=imageForZone(zone);if(img&&img.dataset.src!==src){img.src=src;img.dataset.src=src}const key=`v7:${zone}`;if(svg.dataset.v6Key===key)return;svg.innerHTML=highlightMarkup(zone);svg.setAttribute('viewBox','0 0 1000 1400');svg.dataset.v6Key=key;svg.setAttribute('data-view',backZones.has(zone)?'back':'front')}

  function renderMiniAnatomy(){const main=document.getElementById('anatomyFigure');const wrap=document.querySelector('.mini-anatomy-wrap');const mini=wrap?.querySelector('svg');if(!main||!wrap||!mini)return;const zone=zoneFromClass(main);let img=wrap.querySelector('.v6-mini-photo');if(!img){img=document.createElement('img');img.className='v6-mini-photo';img.alt='';img.decoding='async';img.referrerPolicy='no-referrer';wrap.prepend(img)}const src=imageForZone(zone);if(img.dataset.src!==src){img.src=src;img.dataset.src=src}wrap.dataset.zone=zone;mini.innerHTML=highlightMarkup(zone);mini.setAttribute('viewBox',crops[zone]||crops.generic);mini.setAttribute('class',`anatomy-figure zone-${zone}`);mini.dataset.v6Key=zone;const positioning={shoulders:'translate(-50%,-29%) scale(2.00)',chest:'translate(-50%,-31%) scale(2.08)',back:'translate(-50%,-31%) scale(1.98)',biceps:'translate(-50%,-31%) scale(2.14)',triceps:'translate(-50%,-31%) scale(2.14)',abs:'translate(-50%,-43%) scale(1.94)',glutes:'translate(-50%,-61%) scale(1.88)',quads:'translate(-50%,-68%) scale(1.86)',hamstrings:'translate(-50%,-68%) scale(1.86)',calves:'translate(-50%,-84%) scale(2.02)',generic:'translate(-50%,-50%) scale(1)'};img.style.transform=positioning[zone]||positioning.generic}

  function workoutContext(){const program=window.IRONLOG_PROGRAM||[];const short=(document.getElementById('bigWorkoutTitle')?.textContent||'').trim();const indexText=document.getElementById('exerciseIndex')?.textContent||'';const match=indexText.match(/תרגיל\s+(\d+)/);const index=match?Number(match[1])-1:0;const workout=program.find(w=>String(w.short).trim()===short)||program.find(w=>String(w.title).trim()===short);return{workout,index}}
  function fallbackGroup(exercise){const muscle=String(exercise?.muscle||'');if(muscle.includes('חזה'))return'chest';if(muscle.includes('יד קדמית'))return'biceps';if(muscle.includes('יד אחורית'))return'triceps';if(muscle.includes('גב')||muscle.includes('רחב'))return'back';if(muscle.includes('כתף'))return'shoulders';if(muscle.includes('בטן')||muscle.includes('ליבה'))return'abs';if(muscle.includes('רגל')||muscle.includes('ארבע')||muscle.includes('המסטרינג')||muscle.includes('תאומים')||muscle.includes('ישבן'))return'legs';return'generic'}
  function syncNextThumbnail(){const thumb=document.querySelector('.next-thumb');if(!thumb)return;const{workout,index}=workoutContext();const next=workout?.exercises?.[index+1];if(!next){thumb.innerHTML='<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="18" fill="#10171b"/><path d="M15 25l6 6 13-15" fill="none" stroke="#cfff00" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg>';return}const id=exactThumbs[next.id]||fallbackThumbs[fallbackGroup(next)]||fallbackThumbs.generic;const src=`https://img.youtube.com/vi/${id}/mqdefault.jpg`;const existing=thumb.querySelector('img');if(existing?.dataset.exerciseId===next.id)return;thumb.innerHTML='';const img=document.createElement('img');img.src=src;img.dataset.exerciseId=next.id;img.alt=String(next.name||'Next exercise');img.loading='eager';img.referrerPolicy='no-referrer';img.onerror=()=>{if(img.dataset.fallback==='1')return;img.dataset.fallback='1';img.src=FALLBACK_PHOTO};thumb.appendChild(img)}

  function setupRestControls(){const workoutView=document.getElementById('workoutView');const metric=document.getElementById('restMetric');const controls=document.getElementById('restControls');if(!workoutView||!metric||!controls||metric.dataset.v7Rest==='1')return;metric.dataset.v7Rest='1';workoutView.classList.remove('rest-tools-open');metric.style.cursor='pointer';metric.addEventListener('click',()=>{if(controls.hidden)return;workoutView.classList.toggle('rest-tools-open')});controls.addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',e=>{if(!workoutView.classList.contains('rest-tools-open'))return;if(e.target.closest('#restMetric,#restControls'))return;workoutView.classList.remove('rest-tools-open')});new MutationObserver(()=>{if(controls.hidden)workoutView.classList.remove('rest-tools-open')}).observe(controls,{attributes:true,attributeFilter:['hidden']})}
  function refresh(){renderMainAnatomy();renderMiniAnatomy();syncNextThumbnail();setupRestControls()}
  function boot(){refresh();const target=document.getElementById('workoutView');if(target)new MutationObserver(()=>requestAnimationFrame(refresh)).observe(target,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','data-view']});document.addEventListener('click',e=>{if(e.target.closest('#sheetStartBtn,[data-sheet-ex],#workoutNextBtn,#nextExerciseStrip,[data-pick],#completeSetBtn,#skipSetBtn'))setTimeout(refresh,50)});setInterval(()=>{if(document.getElementById('workoutView')?.classList.contains('active'))refresh()},1100)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();