import { escapeHtml } from '../../core/escape-html.js';
import { Icon } from '../../components/icons.js';
import { AppPageHeader } from '../../components/app-page-header.js';
import { WORKOUTS, workoutForDay, nextWorkoutFromDay } from './workout-catalog.js';

const DAY_LABELS = Object.freeze(['א׳', 'ב׳', 'ג׳', 'ד׳', 'ה׳', 'ו׳', 'ש׳']);
const MONTHS = Object.freeze(['בינו׳', 'בפבר׳', 'במרץ', 'באפר׳', 'במאי', 'ביוני', 'ביולי', 'באוג׳', 'בספט׳', 'באוק׳', 'בנוב׳', 'בדצמ׳']);
function weekDates(selectedDay = new Date().getDay()){const now=new Date(),sunday=new Date(now);sunday.setHours(12,0,0,0);sunday.setDate(now.getDate()-now.getDay());return DAY_LABELS.map((label,day)=>{const date=new Date(sunday);date.setDate(sunday.getDate()+day);return{label,day,date,selected:day===selectedDay}})}
function selectedWorkout(){const today=new Date().getDay();return workoutForDay(today)||nextWorkoutFromDay(today)}
function workoutDate(workout){const today=new Date(),sunday=new Date(today);sunday.setHours(12,0,0,0);sunday.setDate(today.getDate()-today.getDay());const date=new Date(sunday);date.setDate(sunday.getDate()+workout.day);if(workout.day<today.getDay())date.setDate(date.getDate()+7);return date}
function compactTitle(workout){return workout.short.replace(/\s+[AB]$/,'')}
function hebrewTargets(workout){const map={Chest:'חזה',Biceps:'בייספס',Triceps:'טרייספס',Shoulders:'כתפיים',Back:'גב','Rear Delts':'כתף אחורית',Quads:'רגליים',Hamstrings:'המסטרינג',Glutes:'ישבן',Core:'בטן',Calves:'תאומים',Delts:'כתפיים'};return workout.targets.map(t=>map[t]||t).join(' · ')}
function heroSubtitle(w){const l=compactTitle(w);if(l==='ARMS')return'ידיים + כתפיים';if(l==='PUSH')return'חזה + כתפיים';if(l==='PULL')return'גב + ידיים';if(l==='LEGS')return'רגליים + ישבן';return hebrewTargets(w)}
function durationRange(m){return`${Math.max(30,m-16)}–${Math.max(31,m-1)} דק׳`}
function dayStrip(){return weekDates().map(({label,date,selected})=>`<div class="training-day ${selected?'is-selected':''}"><span>${label}</span><strong>${String(date.getDate()).padStart(2,'0')}</strong><i></i></div>`).join('')}
function liveWorkoutFor(displayWorkout,workouts){return workouts.find(i=>i.id===displayWorkout.id)||null}
function hero(workout,workouts,activeSession){const date=workoutDate(workout),today=new Date().toDateString()===date.toDateString(),front=workout.images?.[0]||'',back=workout.images?.[1]||front,liveWorkout=liveWorkoutFor(workout,workouts),templateId=liveWorkout?.databaseId||'',active=Boolean(activeSession);return`<section class="training-hero"><div class="training-hero__copy"><div class="training-hero__date"><strong>${today?'היום':'האימון הבא'}</strong><span>• ${DAY_LABELS[workout.day]}, ${String(date.getDate()).padStart(2,'0')} ${MONTHS[date.getMonth()]}</span></div><h2>${escapeHtml(compactTitle(workout))}</h2><p>${escapeHtml(heroSubtitle(workout))}</p><div class="training-hero__chips"><span>${Icon('clock',{size:13})}<b>${escapeHtml(durationRange(workout.minutes))}</b></span><span><i class="intensity-bars"><b></b><b></b><b></b></i><b>עצימות גבוהה</b></span></div><button class="training-start" type="button" data-start-workout="${templateId}"><span>${active?'המשך אימון':'התחל אימון'}</span><i>→</i></button></div><div class="training-hero__art"><img class="training-hero__back" src="${back}" alt=""><img class="training-hero__front" src="${front}" alt=""></div></section>`}
function summaryTiles(workout){const date=workoutDate(workout);return`<section class="training-summary"><article><i class="summary-icon summary-icon--ring"></i><div><strong>4/6</strong><span>אימונים השבוע</span></div></article><article><i class="summary-icon summary-icon--target"></i><div><strong>PPL</strong><span>ספליט פעיל</span></div></article><article><i class="summary-icon summary-icon--clock">${Icon('clock',{size:17})}</i><div><strong>${escapeHtml(compactTitle(workout))}</strong><span>אימון הבא</span><small>יום ${DAY_LABELS[workout.day]}, ${date.getDate()}</small></div></article></section>`}
function representative(l){if(l==='PUSH')return WORKOUTS.find(i=>i.id==='push-a');if(l==='PULL')return WORKOUTS.find(i=>i.id==='pull-a');if(l==='LEGS')return WORKOUTS.find(i=>i.id==='legs-b');return WORKOUTS.find(i=>i.id==='arms')}
function programRow(label,status,stateClass,workouts,progressText=''){const workout=representative(label),liveWorkout=liveWorkoutFor(workout,workouts),thumb=workout?.images?.[0]||'',action=liveWorkout?.databaseId?`data-open-workout="${liveWorkout.databaseId}"`:'data-demo-action';return`<button class="training-plan-row ${stateClass}" type="button" ${action}><span class="training-plan-row__arrow">‹</span><span class="training-plan-row__copy"><strong>${label}</strong><small>${escapeHtml(hebrewTargets(workout))}</small></span><span class="training-plan-row__progress"><i><b></b><b></b><b></b><b></b><b></b></i><em>${escapeHtml(progressText||status)}</em></span><span class="training-plan-row__state">${status==='הושלם'?'✓':status==='רגליים חלקית'?'3/6':''}</span><span class="training-plan-row__thumb"><img src="${thumb}" alt=""></span></button>`}
function planList(workouts){return`<section class="training-plan"><h3>תוכנית האימונים שלך</h3><div class="training-plan__rows">${programRow('PUSH','הושלם','is-complete',workouts)}${programRow('PULL','הושלם','is-complete',workouts)}${programRow('LEGS','רגליים חלקית','is-partial',workouts,'רגליים חלקית')}${programRow('ARMS','הבא בתור','is-next',workouts,'הבא בתור')}</div></section>`}
function quickStats(){return`<section class="training-quick"><h3>סטטיסטיקות מהירות</h3><div class="training-quick__grid"><article><i class="quick-ring"></i><div><strong>68%</strong><span>השלמת תוכנית</span></div></article><article><i class="quick-wave">⌁</i><div><strong>12,450</strong><span>ק״ג השבוע</span></div></article><article><i class="quick-trophy">◇</i><div><strong>14</strong><span>רצף ימים</span></div></article></div></section>`}
function completedSetCount(s){return s.exercises.reduce((sum,e)=>sum+e.sets.filter(x=>x.completed).length,0)}
function plannedSetCount(s){return s.exercises.reduce((sum,e)=>sum+e.plannedSets,0)}
function currentExercise(s){return s.exercises.find(e=>e.sets.filter(x=>x.completed).length<e.plannedSets)||s.exercises.at(-1)}
function setMap(e){return new Map(e.sets.map(s=>[s.setNumber,s]))}
function targetRepDefault(t){const f=String(t||'').match(/\d+/);return f?Number(f[0]):8}
function lastCompletedSet(e){return[...e.sets].filter(s=>s.completed).sort((a,b)=>b.setNumber-a.setNumber)[0]||null}
function chartData(exercise,activeNumber,load){const done=[...exercise.sets].filter(s=>s.completed).sort((a,b)=>a.setNumber-b.setNumber).slice(-3);let vals=done.map(s=>Number(s.loadKg)||0);if(!vals.length) vals=[Math.max(0,load-5),Math.max(0,load-2.5),load].filter(v=>v||load===0);const points=vals.slice(-3);const all=[...points,load];const max=Math.max(...all,1),min=Math.min(...all,0),span=Math.max(max-min,5);const coords=points.map((v,i)=>({x:12+i*28,y:72-((v-min)/span)*42,v}));const nextX=coords.length?12+coords.length*28:12;const path=coords.length?`M ${coords.map(p=>`${p.x} ${p.y}`).join(' L ')} L ${nextX} 48`:'';return{coords,nextX,path}}
function ActiveWorkoutScreen(session){const exercise=currentExercise(session);if(!exercise)return'';const map=setMap(exercise);let activeSetNumber=1;for(let n=1;n<=exercise.plannedSets;n++){if(!map.get(n)?.completed){activeSetNumber=n;break}activeSetNumber=exercise.plannedSets}const previous=lastCompletedSet(exercise),load=previous?.loadKg??0,reps=previous?.reps??targetRepDefault(exercise.targetReps),rir=previous?.rir??exercise.targetRirMax??2,completed=completedSetCount(session),planned=plannedSetCount(session),percent=planned?Math.round(completed/planned*100):0,nextExercise=session.exercises.find(i=>i.position>exercise.position&&i.sets.filter(s=>s.completed).length<i.plannedSets),graph=chartData(exercise,activeSetNumber,load),hot=exercise.sets.filter(s=>s.completed).length>=3;return`<div class="active-workout-page live-minimal" dir="rtl" data-active-session="${session.id}" data-started-at="${escapeHtml(session.startedAt)}">
<header class="live-workout-header"><button type="button" data-minimize-workout>‹</button><div><strong>${escapeHtml(session.name)}</strong><span><b id="liveWorkoutElapsed">00:00:00</b>　•　${completed}/${planned} תרגילים</span></div><button class="live-more">•••</button></header><div class="live-total-progress"><i style="--progress:${percent}%"></i></div>
<section class="live-hero-flat"><div class="live-ring" style="--ring:${Math.round(((activeSetNumber-1)/exercise.plannedSets)*100)}%"><span>סט נוכחי</span><b><em>${activeSetNumber}</em> / ${exercise.plannedSets}</b></div><div class="live-exercise-name"><h1>${escapeHtml(exercise.name)}</h1><p>${escapeHtml(exercise.targetReps||'לפי התוכנית')}</p></div><div class="live-muscle-figure" aria-hidden="true"><i></i><i></i></div></section>
<section class="live-performance"><svg class="live-chart" viewBox="0 0 100 86" preserveAspectRatio="none"><defs><linearGradient id="liveFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#cfff12" stop-opacity=".18"/><stop offset="1" stop-color="#cfff12" stop-opacity="0"/></linearGradient></defs>${graph.path?`<path class="live-chart-fill" d="${graph.path} L ${graph.nextX} 78 L 12 78 Z"/><path class="live-chart-line" d="${graph.path}"/>`:''}${graph.coords.map((p,i)=>`<circle cx="${p.x}" cy="${p.y}" r="1.7" class="${i===graph.coords.length-1?'hot':''}"/><text x="${p.x}" y="${p.y-7}">${p.v}</text><text x="${p.x}" y="83">סט ${i+1}</text>`).join('')}<circle cx="${graph.nextX}" cy="48" r="2" class="next"/><text x="${graph.nextX}" y="83">סט ${activeSetNumber}</text></svg><div class="live-fire-note">🔥 <span>${hot?'3 הסטים האחרונים שלך? ':'המגמה שלך עולה — '}<b>אתה על אש!</b></span></div></section>
<form class="live-entry-form" data-set-form data-session-exercise-id="${exercise.id}" data-set-number="${activeSetNumber}" data-rest-seconds="${exercise.restMaxSeconds}"><div class="live-inline-fields"><div><label>חזרות</label><input id="liveReps" name="reps" type="number" min="0" value="${reps}" required><p><button type="button" data-step="-1" data-step-target="liveReps">−</button><button type="button" data-step="1" data-step-target="liveReps">＋</button></p></div><div><label>משקל (ק״ג)</label><input id="liveWeight" name="loadKg" type="number" min="0" step="0.25" value="${load}"><p><button type="button" data-step="-2.5" data-step-target="liveWeight">−</button><button type="button" data-step="2.5" data-step-target="liveWeight">＋</button></p></div><div><label>RIR</label><input id="liveRir" name="rir" type="number" min="0" max="10" step="0.5" value="${rir}"><p><button type="button" data-step="-0.5" data-step-target="liveRir">−</button><button type="button" data-step="0.5" data-step-target="liveRir">＋</button></p></div></div><button class="live-save-set" type="submit">שמור סט　✓</button></form>
<section class="live-rest-flat" id="restTimer"><div class="live-rest-ring"><button type="button" id="skipRestTimer">Ⅱ</button></div><div><span>הזמן מנוחה</span><strong id="restTimerValue">${String(Math.floor((exercise.restMaxSeconds||90)/60)).padStart(2,'0')}:${String((exercise.restMaxSeconds||90)%60).padStart(2,'0')}</strong><small>עד הסט הבא</small></div></section>
<section class="live-next-flat"><div><small>הבא</small><strong>${escapeHtml(nextExercise?.name||'סיום האימון')}</strong><span>${nextExercise?escapeHtml(nextExercise.targetReps||''):''}</span></div><b>‹</b></section><button class="live-finish-flat" type="button" data-complete-session="${session.id}">⚑　סיום אימון</button></div>`}
export function WorkoutBuilderExerciseRow(){return''}
export function WorkoutsScreen({workouts=WORKOUTS,workoutData={},ui=null}={}){if(workoutData.activeSession&&ui?.type!=='overview')return ActiveWorkoutScreen(workoutData.activeSession);const workout=selectedWorkout();return`<div class="workouts-concept animate-enter" dir="rtl">${AppPageHeader({title:'אימונים',subtitle:'תכנון. ביצוע. התקדמות.',rootClass:'training-header',brandClass:'training-brand',headingClass:'training-heading'})}<section class="training-calendar"><span class="training-calendar__icon">${Icon('calendar',{size:21})}</span><div class="training-calendar__days">${dayStrip()}</div></section>${hero(workout,workouts,workoutData.activeSession||null)}${summaryTiles(workout)}${planList(workouts)}${quickStats()}</div>`}